#!/bin/sh

mkdir -p bin/bd
case "`uname`" in CYGWIN*) sep=";" ; h=$(cygpath -w "$HOME") ;; *) sep=":"; h=$HOME ;; esac
"$JAVA_HOME/bin/javac" -cp "lib/bd/*${sep}lib/main/*${sep}$h/.bd/*" -sourcepath src/bd -d bin/bd src/bd/*.java
if [ $? == 0 ] ; then
    "$JAVA_HOME/bin/java" -Xmx512m -cp "bin/bd${sep}lib/bd/*${sep}lib/main/*${sep}$h/.bd/*" org.exigencecorp.bd.BuildRunner $*
fi

