
require '../build.rb'

define 'joist-util' do
  project.group = 'joist'
  project.version = THIS_VERSION
  package_with_ivy_pom project
  ivy.compile_conf('default').test_conf('test')
  file _("target/#{project.name}-#{project.version}.pom") => [
    _("target/#{project.name}-#{project.version}.jar"),
    task('ivy:makepom')
  ] do
  end
end

