package joist;

public class Files {

    public static String[] files = new String[] {
        ".classpath",
        ".factorypath",
        ".project",
        ".gitignore",
        "build.properties",
        "build.xml",
        "ivy.xml",
        "ivysettings.xml",
        "ProjectNameCycle.launch",
        "ProjectNameJetty.launch",
        ".settings/org.eclipse.jdt.apt.core.prefs",
        ".settings/org.eclipse.jdt.core.prefs",
        ".settings/org.eclipse.jdt.ui.prefs",
        "content/index.htm",
        "content/WEB-INF/web.xml",
        "src/build/ivybootstrap.xml",
        "src/build/ivytargets.xml",
        "src/build/integration.xml",
        "src/build/main.xml",
        "src/build/unit.xml",
        "src/build/war.xml",
        "src/main/LogConfiguration.java",
        "src/main/projectName/Environment.java",
        "src/main/projectName/Registry.java",
        "src/main/projectName/cli/Cli.java",
        "src/main/projectName/cli/JoistCli.java",
        "src/main/projectName/migrations/m0000.java",
        "src/main/projectName/migrations/m0001.java",
        "src/main/projectName/webapp/ProjectNameServlet.java",
        "src/main/projectName/webapp/pages/AbstractProjectNamePage.java",
        "src/main/projectName/webapp/pages/IndexPage.java",
        "src/main/projectName/webapp/pages/index.htm",
        "tests/unit/projectName/AbstractProjectNameUnitTest.java",
        "tests/unit/projectName/domain/UserTest.java",
        "tests/unit/projectName/domain/builders/UserBuilder.java",
        "tests/integration/projectName/AbstractProjectNameIntegrationTest.java",
        "tests/integration/projectName/domain/UserIntegrationTest.java",
        "tests/web/projectName/AbstractProjectNameWebTest.java",
        "tests/web/projectName/webapp/pageObjects/AbstractProjectNamePageObject.java",
        "tests/web/projectName/webapp/pageObjects/IndexPageObject.java",
        "tests/web/projectName/webapp/pages/IndexPageTest.java" };

}
