
require '../build.rb'

define 'joist-features' do
  project.group = 'joist'
  project.version = THIS_VERSION
  package_with_ivy_pom project
  ivy.compile_conf('default').test_conf('test')
  compile.from _('src/codegen')
end

